/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1;

import javax.swing.Timer;
import com.mycompany.mavenproject1.Dashboard;


/**
 *
 * @author LENOVO
 */
public class LoadingPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoadingPage.class.getName());
    private final java.util.Set<Integer> pausedAt = new java.util.HashSet<>();


    private Timer timer;
    /**
     * Creates new form LoadingPage
     */
    
    public LoadingPage() {
      initComponents();

      jProgressBar1.setMinimum(0);
      jProgressBar1.setMaximum(100);
      jProgressBar1.setValue(0);
      percentage.setText("0%");

      startLoading();
    }

    
     //==========================
    // Loading Function
    //==========================
   private void startLoading() {

    timer = new Timer(50, e -> {

        int value = jProgressBar1.getValue() + 1;

        jProgressBar1.setValue(value);
        percentage.setText(value + "%");

        if (value <= 20) {
            loadingInfo1.setText("Initializing application...");
        } else if (value <= 40) {
            loadingInfo1.setText("Loading system resources...");
        } else if (value <= 60) {
            loadingInfo1.setText("Connecting to database...");
        } else if (value <= 80) {
            loadingInfo1.setText("Preparing examination modules...");
        } else if (value < 100) {
            loadingInfo1.setText("Launching Online Examination System...");
        }

        // Pause at specific percentages
        if ((value == 15 || value == 30 || value == 52 ||
             value == 78 || value == 90 || value == 95)
             && !pausedAt.contains(value)) {

            pausedAt.add(value);

            timer.stop();

            Timer pause = new Timer(10000, ev -> timer.start());
            pause.setRepeats(false);
            pause.start();

            return;
        }
        if (value >= 98) {

            timer.stop();

            jProgressBar1.setValue(100);
            percentage.setText("100%");
            loadingInfo1.setText("Loading Complete.");

            dispose();

            new Dashboard().setVisible(true);
        }
    });

    timer.start();
}
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadingPage = new javax.swing.JPanel();
        loadingTitle = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        subTitle = new javax.swing.JLabel();
        loading = new javax.swing.JLabel();
        percentage = new javax.swing.JLabel();
        description1 = new javax.swing.JLabel();
        loadingInfo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        loadingPage.setBackground(new java.awt.Color(0, 0, 102));

        loadingTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        loadingTitle.setForeground(new java.awt.Color(255, 255, 255));
        loadingTitle.setText("Online Examination System");

        jProgressBar1.addChangeListener(this::jProgressBar1StateChanged);
        jProgressBar1.addPropertyChangeListener(this::jProgressBar1PropertyChange);

        subTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subTitle.setForeground(new java.awt.Color(255, 255, 255));
        subTitle.setText("Providing a secure and reliable examination experience.");

        loading.setForeground(new java.awt.Color(255, 255, 255));
        loading.setText("Loading...");

        percentage.setForeground(new java.awt.Color(255, 255, 255));
        percentage.setText("68%");
        percentage.addPropertyChangeListener(this::percentageIncreament);

        description1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        description1.setForeground(new java.awt.Color(255, 255, 255));
        description1.setText("Loading Application...");

        loadingInfo1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loadingInfo1.setForeground(new java.awt.Color(255, 255, 255));
        loadingInfo1.setText("Please wait this may take a few minutes");

        javax.swing.GroupLayout loadingPageLayout = new javax.swing.GroupLayout(loadingPage);
        loadingPage.setLayout(loadingPageLayout);
        loadingPageLayout.setHorizontalGroup(
            loadingPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadingPageLayout.createSequentialGroup()
                .addGap(0, 139, Short.MAX_VALUE)
                .addGroup(loadingPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadingPageLayout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadingPageLayout.createSequentialGroup()
                        .addComponent(loadingTitle)
                        .addGap(193, 193, 193))))
            .addGroup(loadingPageLayout.createSequentialGroup()
                .addGap(401, 401, 401)
                .addComponent(loading)
                .addGap(18, 18, 18)
                .addComponent(percentage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadingPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loadingPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadingPageLayout.createSequentialGroup()
                        .addComponent(loadingInfo1)
                        .addGap(312, 312, 312))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadingPageLayout.createSequentialGroup()
                        .addComponent(description1)
                        .addGap(371, 371, 371))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadingPageLayout.createSequentialGroup()
                        .addComponent(subTitle)
                        .addGap(263, 263, 263))))
        );
        loadingPageLayout.setVerticalGroup(
            loadingPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadingPageLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(loadingTitle)
                .addGap(37, 37, 37)
                .addComponent(subTitle)
                .addGap(18, 18, 18)
                .addComponent(description1)
                .addGap(18, 18, 18)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(loadingPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loading)
                    .addComponent(percentage))
                .addGap(18, 18, 18)
                .addComponent(loadingInfo1)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadingPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loadingPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jProgressBar1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jProgressBar1PropertyChange
        // TODO add your handling code here:
        int value = jProgressBar1.getValue();
          percentage.setText(value + "%");

    }//GEN-LAST:event_jProgressBar1PropertyChange

    private void jProgressBar1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jProgressBar1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jProgressBar1StateChanged

    private void percentageIncreament(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_percentageIncreament
        // TODO add your handling code here:
//            int value = jProgressBar1.getValue();
//
//            if(value < 100){
//
//                jProgressBar1.setValue(value + 1);
//
//            } else {
//
//                timer.stop();
//
//                login loginPage = new login();
//                loginPage.setVisible(true);
//
//                this.dispose();
//            }

    }//GEN-LAST:event_percentageIncreament

     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {

                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }

        } catch (ReflectiveOperationException |
                 javax.swing.UnsupportedLookAndFeelException ex) {

            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new LoadingPage().setVisible(true);
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel description1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel loading;
    private javax.swing.JLabel loadingInfo1;
    private javax.swing.JPanel loadingPage;
    private javax.swing.JLabel loadingTitle;
    private javax.swing.JLabel percentage;
    private javax.swing.JLabel subTitle;
    // End of variables declaration//GEN-END:variables
}
